# Generated by Django 5.0 on 2023-12-16 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('sobrenome', models.CharField(max_length=50)),
                ('matricula', models.CharField(max_length=8)),
                ('cargo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Funcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcao', models.CharField(max_length=50)),
                ('lotacao', models.CharField(max_length=50)),
                ('turno', models.CharField(max_length=50)),
                ('cadastro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.cadastro')),
            ],
        ),
    ]
