# Generated by Django 5.0 on 2023-12-16 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('sobrenome', models.CharField(max_length=50)),
                ('matricula', models.CharField(max_length=8, unique=True)),
                ('cargo', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='funcao',
            name='cadastro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.professor'),
        ),
        migrations.DeleteModel(
            name='Cadastro',
        ),
    ]
