# Generated by Django 4.2.7 on 2023-12-12 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcao',
            name='turno',
            field=models.CharField(),
        ),
    ]
