# Generated by Django 5.0 on 2023-12-16 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_professor_alter_funcao_cadastro_delete_cadastro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funcao',
            old_name='cadastro',
            new_name='ptofessor',
        ),
    ]
