# Generated by Django 4.2.7 on 2023-12-15 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0003_alter_funcao_turno'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastro',
            name='matricula',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
